version: '2'

services:
  server:
    container_name: recycling-server
    # Override Dockerfile default command in dev
    command: bash -c "./wait-for-it.sh db:3306 -t 60 -- bundle install && bin/rake db:migrate && bin/rake db:seed && bundle exec rails s -p 3000"
    build: ./recycling-server
    image: zhzhang2012/cs121-recycling-server:v1
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
    env_file:
      - ".env"
    ports:
      - 3000:3000
    volumes:
      - ./recycling-server:/srv/server
      - /srv/server/tmp

  db:
    container_name: db-mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=recycling-app-dev-MySQL-SECRET
      - MYSQL_DATABASE=recycling-app-dev
      - MYSQL_USER=dbdevmaster
      - MYSQL_PASSWORD=dbdevmaster
    ports:
      - 3306:3306

  search:
    container_name: search-elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    ports:
      - 9200:9200
    environment:
      - cluster.name=search-elastic-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
